name: CI

on:
  push:
    branches:
     - main
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v5
    with:
      lint: true
      auto-merge-exclude: 'help-me'
