name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@fe0ddd11457da428e0fed73efba2ca36baec15ed
    with:
      lint: true
      auto-merge-exclude: 'help-me'
