name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@08b952949884ac4cf72ab0ca2ce88b058b7976cd
    with:
      lint: true
      auto-merge-exclude: 'help-me'
