name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@d452e942a2175bd44b96508366e1752a228a1246
    with:
      lint: true
      auto-merge-exclude: 'help-me'
