name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@04a2d6ae69784b9dd665456e01b45e3b1b839a53
    with:
      lint: true
      auto-merge-exclude: 'help-me'
