name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@9cb42e35cca3b09ac043d0d139db50930f8117a7
    with:
      lint: true
      auto-merge-exclude: 'help-me'
